= Caltic Vert.x Starter

This project is a template to start your own Vert.x project using Apache Maven.

== Build Status

* `master` image:https://travis-ci.org/h3rucutu/caltic-vertx-starter.svg?branch=master["Build Status", link="https://travis-ci.org/h3rucutu/caltic-vertx-starter"]
* `develop` image:https://travis-ci.org/h3rucutu/caltic-vertx-starter.svg?branch=develop["Build Status", link="https://travis-ci.org/h3rucutu/caltic-vertx-starter"]

== Prerequisites

* Apache Maven
* JDK 8+

== Getting started

Create your project with:

[source]
----
git clone https://github.com/h3rucutu/caltic-vertx-starter.git `PROJECT_NAME`
----

Replace `PROJECT_NAME` with the name of your project.

== Running the project

Once you have retrieved the project, enter into your project then you can check that everything works with:

[source]
----
./mvnw clean compile vertx:run
----

On Windows:

[source]
----
mvnw.cmd clean compile vertx:run
----

The command compiles the project and run it in redeploy mode. Open your browser to http://localhost:9000[http://localhost:9000]. You should see a `Hello Caltic Vert.x!` message.

Redeploy mode helps developer to compile immediately when there's a changes and deploy it automatically, usually called `hot-reload`.

Besides run in redeploy mode, you also can package into one `jar` file:

[source]
----
./mvnw clean compile vertx:package
----

On Windows:

[source]
----
mvnw.cmd clean compile vertx:package
----

And run it with `java -jar` command:

[source]
----
java -jar target/*jar
----

== Anatomy of the project

The project contains:

* a `pom.xml` file
* a _main_ verticle file (https://github.com/h3rucutu/caltic-vertx-starter/blob/master/src/main/java/id/caltic/labs/MainVerticle.java[`MainVerticle.java`])
* an unit test (https://github.com/h3rucutu/caltic-vertx-starter/blob/master/src/test/java/id/caltic/labs/MainVerticleTest.java[`MainVerticleTest.java`])

== Start to hack

1. Delete the `.git` directory:
2. Open the `pom.xml` file and customize the `groupId`, `artifactId` and `version`. You can also change the `main.verticle` property to use your own package name and verticle class.
3. After editing `pom.xml` file, change necessary directory under `src/main/java` and `src/test/java` following your `groupId`.
4. Save all your work and try to run.

== Git-Flow

This project is maintained using https://github.com/nvie/gitflow[git-flow]. Please refer `git-flow` website for the instructions.

== Caltic.id

This project brought to you by https://caltic.id[caltic.id]